version: "3.9"

services:
  # PHP-FPM (Laravel)
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    image: bussaty-php:8.2
    container_name: bussaty_app
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      PHP_MEMORY_LIMIT: 512M
      COMPOSER_ALLOW_SUPERUSER: "1"
      COMPOSER_CACHE_DIR: /tmp/composer
    volumes:
      - ./laravel:/var/www/html
      - composer-cache:/tmp/composer
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Nginx (backend web server)
  web:
    image: nginx:1.25-alpine
    container_name: bussaty_web
    volumes:
      - ./laravel:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Public Edge (SSL + routing)
  caddy:
    image: caddy:2-alpine
    container_name: bussaty_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      web:
        condition: service_started
      socket:
        condition: service_started
    restart: unless-stopped

  # MySQL
  db:
    image: mysql:8.0
    container_name: bussaty_db
    environment:
      MYSQL_DATABASE: bussaty
      MYSQL_USER: bussaty
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -ubussaty -psecret --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    container_name: bussaty_redis
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Laravel queue worker
  queue:
    image: bussaty-php:8.2
    container_name: bussaty_queue
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    command: php artisan queue:work --sleep=1 --tries=3
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped

  # Laravel scheduler
  scheduler:
    image: bussaty-php:8.2
    container_name: bussaty_scheduler
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    command: php artisan schedule:work
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: bussaty_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Node Socket.IO service (private; proxied by Caddy)
  socket:
    build:
      context: ./node-socket
      dockerfile: Dockerfile
    image: bussaty-socket:20
    container_name: bussaty_socket
    working_dir: /usr/src/app
    environment:
      PORT: 3001
      NODE_ENV: production
      CORS_ORIGINS: "https://app.elbayoumi.net,https://ws.app.elbayoumi.net"
    volumes:
      - ./node-socket:/usr/src/app
    expose:
      - "3001"  # internal only; Caddy proxies
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3001/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
  composer-cache:
  caddy-data:
  caddy-config:
